### ISSUE TITLE
Depreciated: npm extension

### ISSUE THREAD

**Issue by a2937** [jawandarajbir/react-vscode-extension-pack#5]
The following extension: [npm](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script)
is now depreciated because it's base functionality is now being provided out of the box from VS Code. Would you please kindly remove it from your package please?

**Comment by jawandarajbir** [comment]
I've published a new version in VS Code marketplace. Thanks for your contribution @a2937 👍🏼
